/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'Root': RouteRecordInfo<'Root', '/', Record<never, never>, Record<never, never>>,
    '$All': RouteRecordInfo<'$All', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    'DocsParent': RouteRecordInfo<'DocsParent', '/docs', Record<never, never>, Record<never, never>>,
    'Docs': RouteRecordInfo<'Docs', '/docs', Record<never, never>, Record<never, never>>,
    'DocsChecklist': RouteRecordInfo<'DocsChecklist', '/docs/checklist', Record<never, never>, Record<never, never>>,
    'DocsForms': RouteRecordInfo<'DocsForms', '/docs/forms', Record<never, never>, Record<never, never>>,
    'DocsUsage': RouteRecordInfo<'DocsUsage', '/docs/usage', Record<never, never>, Record<never, never>>,
  }
}
