/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    PjCodeBlock: typeof import('./components/PjCodeBlock.vue')['default']
    PjCreateUserForm: typeof import('./components/PjCreateUserForm.vue')['default']
    PjFooter: typeof import('./components/PjFooter.vue')['default']
    PjHeader: typeof import('./components/PjHeader.vue')['default']
    PjNavbar: typeof import('./components/PjNavbar.vue')['default']
    PjSidebar: typeof import('./components/PjSidebar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VvAccordion: typeof import('@volverjs/ui-vue/components')['VvAccordion']
    VvAction: typeof import('@volverjs/ui-vue/components')['VvAction']
    VvAlert: typeof import('@volverjs/ui-vue/components')['VvAlert']
    VvAlertGroup: typeof import('@volverjs/ui-vue/components')['VvAlertGroup']
    VvButton: typeof import('@volverjs/ui-vue/components')['VvButton']
    VvButtonGroup: typeof import('@volverjs/ui-vue/components')['VvButtonGroup']
    VvCard: typeof import('@volverjs/ui-vue/components')['VvCard']
    VvCheckboxGroup: typeof import('@volverjs/ui-vue/components')['VvCheckboxGroup']
    VvDialog: typeof import('@volverjs/ui-vue/components')['VvDialog']
    VvForm: typeof import('@volverjs/ui-vue/components')['VvForm']
    VvFormField: typeof import('@volverjs/ui-vue/components')['VvFormField']
    VvFormWrapper: typeof import('@volverjs/ui-vue/components')['VvFormWrapper']
    VvIcon: typeof import('@volverjs/ui-vue/components')['VvIcon']
    VvRadioGroup: typeof import('@volverjs/ui-vue/components')['VvRadioGroup']
  }
}
