/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    PjCodeBlock: typeof import('./components/PjCodeBlock.vue')['default']
    PjFooter: typeof import('./components/PjFooter.vue')['default']
    PjHeader: typeof import('./components/PjHeader.vue')['default']
    PjNavbar: typeof import('./components/PjNavbar.vue')['default']
    PjSidebar: typeof import('./components/PjSidebar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VvAccordion: typeof import('@volverjs/ui-vue/vv-accordion')['default']
    VvAction: typeof import('@volverjs/ui-vue/vv-action')['default']
    VvAlertGroup: typeof import('@volverjs/ui-vue/vv-alert-group')['default']
    VvButton: typeof import('@volverjs/ui-vue/vv-button')['default']
    VvButtonGroup: typeof import('@volverjs/ui-vue/vv-button-group')['default']
    VvCard: typeof import('@volverjs/ui-vue/vv-card')['default']
    VvCheckboxGroup: typeof import('@volverjs/ui-vue/vv-checkbox-group')['default']
  }
}
